#include<iostream.h>
#include<conio.h>
#include<dos.h>
#include<fstream.h>
void abc();
int main()
{
textbackground(RED);
textcolor(BLUE);
clrscr();
textbackground(BLUE);
cprintf("      ");

textbackground(WHITE);

textcolor(BLUE+BLINK);
cprintf(         "                  EAT STREET RESTAURANT                             " );
textbackground(BLUE);
cprintf("      ");

textbackground(BLUE);
cprintf("      ");


textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                   PUNJABI BAGH BRANCH                              " );
textbackground(BLUE);
cprintf("      ");
textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(MAGENTA+BLINK);

cprintf(         "MANAGER: ARSHDEEP SINGH                 ASS.MANAGER: VAIBHAV SADANA " );
textbackground(BLUE);
cprintf("      ");


 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "CONTACT US: (EMAIL:eatstreet@gmail.com)         (PHONE:011-45530660)" );
textbackground(BLUE);
cprintf("      ");




 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");


 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");

 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");

 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");

 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");

 textbackground(BLUE);
cprintf("      ");



textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");

 textbackground(BLUE);
cprintf("      ");


textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
textbackground(BLUE);
cprintf("      ");

 textbackground(BLUE);
cprintf("      ");


getch();
abc();

getch();
return 0;
}
void abc()
{
textbackground(WHITE);

textcolor(GREEN+BLINK);

cprintf(         "                                                                    " );
cout<<"t";
delay(80);
clrscr();
cout<<"et";
delay(80);
clrscr();
cout<<"eet";
delay(80);
clrscr();
cout<<"reet";
delay(80);
clrscr();
cout<<"treet";
delay(80);
clrscr();
cout<<"Street";
delay(80);
clrscr();
cout<<"t Street";
delay(80);
clrscr();
cout<<"at Street";
delay(80);
clrscr();


cout<<"Eat Street";
delay(80);
clrscr();
cout<<" Eat Street";
delay(80);
clrscr();
cout<<"  Eat Street";
delay(80);
clrscr();
cout<<"   Eat Street";
delay(80);
clrscr();
cout<<"    Eat Street";
delay(80);
clrscr();
cout<<"     Eat Street";
delay(80);
clrscr();
cout<<"      Eat Street";

delay(80);
clrscr();
cout<<"       Eat Street";
delay(80);
clrscr();
cout<<"        Eat Street";
delay(80);
clrscr();
cout<<"         Eat Street";
delay(80);
clrscr();
cout<<"          Eat Street";
delay(80);
clrscr();
cout<<"           Eat Street";
delay(80);
clrscr();
cout<<"            Eat Street";
delay(80);
clrscr();
cout<<"             Eat Street";
delay(80);
clrscr();
cout<<"              Eat Street";
delay(80);
clrscr();
cout<<"               Eat Street";
delay(80);
clrscr();
cout<<"                Eat Street";
delay(80);
clrscr();
cout<<"                 Eat Street";
delay(80);
clrscr();
cout<<"                  Eat Street";
delay(80);
clrscr();
cout<<"                   Eat Street";
delay(80);
clrscr();
cout<<"                    Eat Street";
delay(80);
clrscr();
cout<<"                     Eat Street";
delay(80);
clrscr();
cout<<"                      Eat Street";
delay(80);
clrscr();
cout<<"                       Eat Street";
delay(80);
clrscr();
cout<<"                        Eat Street";
delay(80);
clrscr();
cout<<"                         Eat Street";
delay(80);
clrscr();
cout<<"                          Eat Street";
delay(80);
clrscr();
cout<<"                           Eat Street";
delay(80);
clrscr();
cout<<"                            Eat Street";
delay(80);
clrscr();
cout<<"                             Eat Street";
delay(80);
clrscr();
cout<<"                               Eat Street";
delay(80);
clrscr();
cout<<"                                 Eat Street";

delay(80);
clrscr();
cout<<"                                  Eat Street";
delay(80);
clrscr();
cout<<"                                    Eat Street";
delay(80);
clrscr();
cout<<"                                     Eat Street";
delay(80);
clrscr();
cout<<"                                      Eat Street";
delay(80);
clrscr();
cout<<"                                       Eat Street";

delay(80);
delay(80);
clrscr();
cout<<"                                        Eat Street";
delay(80);
clrscr();
cout<<"                                         Eat Street";
clrscr();
cout<<"                                          Eat Street";
delay(80);
clrscr();
cout<<"                                           Eat Street";
delay(80);
clrscr();
cout<<"                                            Eat Street";
delay(80);
clrscr();
cout<<"                                             Eat Street";
delay(80);
clrscr();
cout<<"                                              Eat Street";
delay(80);
clrscr();
cout<<"                                               Eat Street";
delay(80);
clrscr();
cout<<"                                                Eat Street";
delay(80);
clrscr();
cout<<"                                                 Eat Street";
delay(80);
clrscr();
cout<<"                                                   Eat Street";
delay(80);
clrscr();
cout<<"                                                    Eat Street";
delay(80);
clrscr();
cout<<"                                                     Eat Street";
delay(80);
clrscr();
cout<<"                                                      Eat Street";
delay(80);
clrscr();
cout<<"                                                       Eat Street";
delay(80);
clrscr();
cout<<"                                                        Eat Street";
delay(80);
clrscr();
cout<<"                                                         Eat Street";
delay(80);
clrscr();
cout<<"                                                          Eat Street";
delay(80);
clrscr();
cout<<"                                                           Eat Street";
delay(80);
clrscr();
cout<<"                                                            Eat Street";
delay(80);
clrscr();
cout<<"                                                             Eat Street";
delay(80);
clrscr();
cout<<"                                                              Eat Street";
delay(80);
clrscr();
cout<<"                                                                Eat Street";
delay(80);
clrscr();
cout<<"                                                                  Eat Street";
delay(80);
clrscr();
cout<<"                                                                    Eat Street";
delay(80);
clrscr();
cout<<"                                                                     Eat Street";
delay(80);
clrscr();
cout<<"                                                                      Eat Street";

delay(80);
clrscr();
cout<<"                                                                       Eat Stree";
delay(80);
clrscr();
cout<<"                                                                        Eat Stre";
delay(80);
clrscr();
cout<<"                                                                         Eat Str";
delay(80);
clrscr();
cout<<"                                                                          Eat St";
delay(80);
clrscr();
cout<<"                                                                           Eat S";
delay(80);
clrscr();
cout<<"                                                                            Eat ";
delay(80);
clrscr();
cout<<"                                                                             Eat";
delay(80);
clrscr();
cout<<"                                                                              Ea";
delay(80);
clrscr();
cout<<"                                                                               E";
delay(80);
clrscr();
cout<<"                                                                                ";
for(int i=0;i<22;i++)
cout<<"\n";
cprintf("Menu is Loading..");
for(int j=0;j<=60;j++)
{
textcolor(2);
cprintf("Þ");
delay(100);

}
getch();
textbackground(YELLOW);
textcolor(BLUE);
clrscr();
char ch;
cout<<"\nWhich type of food u want...";
cout<<"\nThe Categories are as follows:";
cout<<"\n1.Vegetarian food";
cout<<"\n2.Non-Vegetarian food";
cout<<"\n3.Special Offers ";
cout<<"\n4.Exit";
cout<<"\nEnter your choice:";
textbackground(BLUE);

cin>>ch;
switch(ch)
{
case '1':cout<<"Vegetarian";
getch();

cout<<"                    \n\t\t\t         VEG.MENU               ";
cout<<"                         \t\t\t                ";
cout<<" \n\n      VEG MEALS                                   SHAKES $ DRINKS                 "        ;
cout<<"                                                                         "        ;
cout<<"\n a.  Aloo Tikki           Rs.30        | f.  Mango shake         Rs.60                    "               ;
cout<<"\n b.  Masala Grilled       Rs.40        | g.  Lime Juice          Rs.50              "              ;
cout<<"\n c.  Rice and Curry       Rs.80        | h.  Faluda drink        Rs.90                      "           ;
cout<<"\n d.  French Fries         Rs.60        | h.  Crusher drink       Rs.70             "     ;
cout<<"\n e.  Veg Wrap             Rs.75        | i. Chocolate mix       Rs.40 "       ;
cout<<"\n\n       Meal Combos                                    Deserts   ";
cout<<"\n       -----------	                              -------     ";
cout<<"\n j.Combo 1:Veg combo       Rs.200     | m.Choco Cake            Rs.40            ";
cout<<"\n k.Combo 2:Spl.VEG Thali   Rs.250     | n.Donuts                Rs.30                  ";
cout<<"\n l.Happy Meal              Rs.180     | o.Nutty Cake            Rs.60   " ;
ofstream obj("ARSHDEEP.TXT",ios::out);

int no,sum=0;
char c,r;

do
{
cout<<"\n\n***PLEASE PLACE AN ORDER***";
cout<<"\nENTER THE CODE OF THE ITEM";

cin>>c;
switch(c)
{
case 'a':cout<<"\n1. Aloo Tikki           Rs.30    ";

cout<<"\nENTER THE NO OF PIECES";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*30;
cout<<"\nTOTAL BILL :"<<sum;
break;
case 'b':cout<<"\n2.Masala Grilled       Rs.40  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*40;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'c':cout<<"\n3. Rice and Curry       Rs.80   ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*80;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'd':cout<<"\n 4.  French Fries         Rs.60     ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*60;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'e':cout<<"\n 5.  Veg Wrap             Rs.75  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*75;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'f':cout<<" 6.  Mango shake         Rs.60      ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*60;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'g':cout<<" 7.  Lime Juice          Rs.50 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*50;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'h':cout<<" 8.  Faluda drink        Rs.90       ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";

cin>>r;
sum+=no*90;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'i':cout<<" 9.  Crusher drink       Rs.70     ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*70;
cout<<"\nTOTAL BILL :"<<sum;

break;

case 'j':cout<<"10. Chocolate mix       Rs.40 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*40;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'k':cout<<"\n 11.Combo 1:Veg combo       Rs.200 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*200;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'l':cout<<"\n 12.Combo 2:Spl.VEG Thali   Rs.250  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*250;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'm':cout<<"\n 13.Happy Meal              Rs.180 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*180;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'n':cout<<"14.Choco Cake            Rs.40   ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*40;
cout<<"\nTOTAL BILL :"<<sum;

break;


case 'o':cout<<" 15.Donuts                Rs.30  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*30;
cout<<"\nTOTAL BILL :"<<sum;

break;




case 'p':cout<<"16.Nutty Cake            Rs.60 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*60;
cout<<"\nTOTAL BILL :"<<sum;

break;




}
getch();
delay(10);
}while((r=='y')||(r=='Y')); //switch inner ends
delay(15000);
break;
case '2':cout<<"Non-Vegetarian";


cout<<"                    \n\t\t\t       	NON-VEG.MENU               ";
cout<<"                         \t\t\t                 ";
cout<<" \n\n    NON-VEG MEALS                                   SHAKES $ DRINKS                 "        ;
cout<<"                                                                     "        ;
cout<<"\n a.  CHIC Tikki           Rs.30        | f.  Mango shake         Rs.60                    "               ;
cout<<"\n b.  Chicken Grilled      Rs.40        | g.  Lime Juice          Rs.50              "              ;
cout<<"\n c.  Rice and Curry CHIC  Rs.80        | h.  Faluda drink        Rs.90                      "           ;
cout<<"\n d.  French Fries         Rs.60        | i.  Crusher drink       Rs.70             "     ;
cout<<"\n e.  NON-Veg Wrap         Rs.75        | j. Chocolate mix       Rs.40 "       ;
cout<<"\n\n       Meal Combos                                    Deserts   ";
cout<<"\n       -----------	                              -------     ";
cout<<"\n k.Combo 1:NON-Veg combo      Rs.200  | n.Choco Cake            Rs.40            ";
cout<<"\n l.Combo 2:Spl.NON-VEG Thali  Rs.250  | o.Donuts                Rs.30                  ";
cout<<"\n m.Happy Meal                 Rs.180  | p.Nutty Cake            Rs.60   ";

int no1,sum1=0;
char c1,r1;

do
{
cout<<"\n\n***PLEASE PLACE AN ORDER***";
cout<<"\nENTER THE CODE OF THE ITEM";

cin>>c1;
switch(c1)
{
case 'a':cout<<"\n1. Aloo Tikki           Rs.30    ";

cout<<"\nENTER THE NO OF PIECES";
cin>>no1;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r1;
sum1+=no1*30;
cout<<"\nTOTAL BILL :"<<sum;
break;
case 'b':cout<<"\n2.Masala Grilled       Rs.40  ";
cin>>no1;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r1;

sum1+=no1*40;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'c':cout<<"\n3. Rice and Curry       Rs.80   ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*80;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'd':cout<<"\n 4.  French Fries         Rs.60     ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*60;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'e':cout<<"\n 5.  Veg Wrap             Rs.75  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;

sum+=no*75;

cout<<"\nTOTAL BILL :"<<sum;
break;
case 'f':cout<<" 6.  Mango shake         Rs.60      ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*60;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'g':cout<<" 7.  Lime Juice          Rs.50 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*50;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'h':cout<<" 8.  Faluda drink        Rs.90       ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";

cin>>r;
sum+=no*90;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'i':cout<<" 9.  Crusher drink       Rs.70     ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*70;
cout<<"\nTOTAL BILL :"<<sum;

break;

case 'j':cout<<"10. Chocolate mix       Rs.40 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*40;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'k':cout<<"\n 11.Combo 1:Veg combo       Rs.200 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*200;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'l':cout<<"\n 12.Combo 2:Spl.VEG Thali   Rs.250  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*250;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'm':cout<<"\n 13.Happy Meal              Rs.180 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*180;
cout<<"\nTOTAL BILL :"<<sum;

break;
case 'n':cout<<"14.Choco Cake            Rs.40   ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*40;
cout<<"\nTOTAL BILL :"<<sum;

break;


case 'o':cout<<" 15.Donuts                Rs.30  ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*30;
cout<<"\nTOTAL BILL :"<<sum;

break;




case 'p':cout<<"16.Nutty Cake            Rs.60 ";
cin>>no;
cout<<"\nWANT TO ENTER MORE....(y\n)?";
cin>>r;
sum+=no*60;
cout<<"\nTOTAL BILL :"<<sum;

break;




}
getch();
delay(10);
}while((r=='y')||(r=='Y')); //switch inner ends
delay(15000);
break;
  textcolor(RED);
textbackground(WHITE);

 clrscr();
getch();
}

